config/routes.rb
Rails.application.routes.draw do
  resources :articles
  devise_for :users, controllers: {
        sessions: 'users/sessions'
  }
  root 'articles#index'
  get 'show' => 'top#show'
  get 'smart'=> 'top#index'
  #get 'users/seccitons/show'


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/article.rb
class Article < ApplicationRecord
  belongs_to :user
  belongs_to :location
  validates :user_id, presence: true
  validates :title, presence: true
  validates :text, presence: true
  mount_uploader :image, ImageUploader

  module ArticleDecorator
    def publication_status
      if published?
        "Published at #{published_at.strftime('%A, %B %e')}"
      else
        "Unpublished"
      end
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]
  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
    save_log if user_signed_in?
  end

  # GET /articles/new
  def new
    @article  = Article.new
    @location = Location.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)
    @location = Location.new(location_params)

    if existed_location = Location.where(name: @location.name).first
      @article.location_id = existed_location.id
    else
      new_location = Location.create(location_params)
      @article.location_id = new_location.id
    end

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article)["user_id"] = current_user.id
      params.require(:article).permit(:title, :text, :user_id, :image)
    end

    def location_params
      params.require(:location).permit(:name)
    end

    def save_log
      ActionLog.create!(
        datetime: Time.zone.now,
        article_id: params[:id],
        user_id: current_user[:id],
        delete: false
        )
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.haml
= form_for @article do |f|
  - if @article.errors.any?
    #error_explanation
      %h2= "#{pluralize(@article.errors.count, "error")} prohibited this article from being saved:"
      %ul
        - @article.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :text
    = f.text_field :text
  .field
    = f.label :image
    = f.file_field :image
  .field
    = fields_for @location do |c|
      = c.text_field :name, :id => "textField"
  %script{:src => "http://maps.googleapis.com/maps/api/js?libraries=places", :type => "text/javascript"}
  .actions
    = f.submit 'Save'

app/views/articles/_image_list.html.haml
- articles = has_image_article
.image_lists
  - articles.each do |article|
    .margin_bottom10
      = link_to (image_tag article.image_url(:thumb)), article, class: "margin_bottom10"

app/views/articles/_right_menu.html.haml
%h1 急上昇
%ul
  %li 近場で盛り上がっている所
  %li 近場の会話

app/views/articles/edit.html.haml
%h1 Editing article

= render 'form'

= link_to 'Show', @article
\|
= link_to 'Back', articles_path

app/views/articles/index.html.haml
%h1 タイムライン
.article_index
  .image_list
    = render "image_list"
  .right_box
    .right_menu
      = render "right_menu"
    .banner0
      = link_to image_tag("banner/banner1.jpg"), root_path

app/views/articles/new.html.haml
%h1 New article

= render 'form'
= link_to 'Back', articles_path

app/views/articles/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @article.title
%p
  %b Text:
  = @article.text
- if @article.image.present?
  %p
    %b Image:
    = image_tag @article.image.url

%p
  %b Location:
  = @article.location.name

= link_to 'Edit', edit_article_path(@article)
\|
= link_to 'Back', articles_path